# Generated by Django 2.0.4 on 2018-06-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(default='NA', max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('tr_essay', models.CharField(default='-', max_length=300)),
                ('contingency', models.CharField(max_length=5)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
