# Generated by Django 2.0.4 on 2018-06-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20180608_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapplication',
            name='type_reim',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
