# Generated by Django 2.0.4 on 2018-07-14 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_trapplication_type_reim'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapplication',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trapplication',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trapplication',
            name='receipt_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trapplication',
            name='reimburse_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trapplication',
            name='travel_date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trapplication',
            name='travel_date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trapplication',
            name='travel_location_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trapplication',
            name='travel_location_state',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
