# Generated by Django 2.0.4 on 2018-07-14 01:53

from django.db import migrations
import django.utils.timezone
import travel.formatcheck


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20180714_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapplication',
            name='receipt_file',
            field=travel.formatcheck.ContentTypeRestrictedFileField(default=django.utils.timezone.now, upload_to='receipts'),
            preserve_default=False,
        ),
    ]
