# Generated by Django 2.0.4 on 2018-09-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20180901_0459'),
        ('travel', '0006_auto_20180723_2337'),
    ]

    operations = [
    ]
