# Generated by Django 2.0.4 on 2018-04-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_application_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contingency',
        ),
    ]
