# Generated by Django 2.0.4 on 2018-04-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_application_contingency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='team',
        ),
    ]
