# Generated by Django 2.0.4 on 2018-04-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_application_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='track',
        ),
    ]
