# Generated by Django 2.0.4 on 2018-04-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180424_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank='False', default='nothing', upload_to='resume'),
        ),
    ]
