# Generated by Django 2.0.4 on 2018-04-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_application_essay1'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='essay2',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='essay3',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
