# Generated by Django 2.0.4 on 2018-04-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180424_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(default='nothing', upload_to='resume'),
        ),
    ]
