# Generated by Django 2.0.4 on 2018-04-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180424_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
    ]
