# Generated by Django 2.0.4 on 2018-04-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180424_0651'),
        ('home', '0010_application_first_name'),
    ]

    operations = [
    ]
