# Generated by Django 2.0.4 on 2018-04-26 02:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_20180425_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='address2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='graduating_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='major',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='reimbursement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=home.formatChecker.ContentTypeRestrictedFileField(upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='university',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='zipcode',
            field=models.CharField(max_length=50),
        ),
    ]
