# Generated by Django 2.0.4 on 2018-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_application_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='secondmajor',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
