# Generated by Django 2.0.4 on 2018-05-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_application_secondmajor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='application',
            name='permission',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='graduating_class',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
