# Generated by Django 2.0.4 on 2018-05-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180503_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='permission',
            field=models.BooleanField(default=True),
        ),
    ]
