# Generated by Django 2.0.4 on 2018-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180503_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='conduct',
            field=models.BooleanField(default=True),
        ),
    ]
