# Generated by Django 2.0.4 on 2018-05-12 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_application_conduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_submission',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
