# Generated by Django 2.0.4 on 2018-06-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_application_date_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='date_submission',
            new_name='submit_time',
        ),
    ]
