# Generated by Django 2.0.4 on 2018-06-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180606_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='how_heard_medhacks',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
