# Generated by Django 2.0.4 on 2018-06-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_20180607_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birthday',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='race',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
