# Generated by Django 2.0.4 on 2018-06-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180620_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='essay1',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AlterField(
            model_name='application',
            name='essay2',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AlterField(
            model_name='application',
            name='essay3',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AlterField(
            model_name='application',
            name='essay4',
            field=models.CharField(default='-', max_length=350),
        ),
    ]
