# Generated by Django 2.0.4 on 2018-09-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180901_0459'),
        ('home', '0025_auto_20180907_1343'),
    ]

    operations = [
    ]
