# Generated by Django 2.0.4 on 2018-04-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180414_1233'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='campus_ambassador',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('-', 'Not Decided')], default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_reimbursement',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('-', 'Not Decided')], default='-', max_length=1),
        ),
    ]
