# Generated by Django 2.0.4 on 2018-04-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180415_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('-', 'Not Decided')], default='-', max_length=1),
        ),
    ]
