# Generated by Django 2.0.4 on 2018-06-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180605_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='travel_reimbursement',
            field=models.CharField(choices=[('-', 'Not Decided'), ('Rejected', 'Rejected'), ('Regional', 'Regional'), ('National', 'National'), ('International', 'International')], default='-', max_length=13),
        ),
    ]
