# Generated by Django 2.0.4 on 2018-06-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180602_2225'),
        ('accounts', '0006_auto_20180606_2147'),
    ]

    operations = [
    ]
