# Generated by Django 2.0.4 on 2018-06-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180608_2045'),
        ('accounts', '0007_merge_20180607_2302'),
    ]

    operations = [
    ]
