# Generated by Django 2.0.4 on 2018-07-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20180620_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('-', 'Not Decided')], default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receipt_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='travel_reimbursement',
            field=models.CharField(choices=[('-', 'Not Decided'), ('Rejected', 'Rejected'), ('Regional', 'Regional'), ('Midwest', 'Midwest'), ('West', 'West'), ('International', 'International')], default='-', max_length=13),
        ),
    ]
