# Generated by Django 2.0.4 on 2018-06-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20180609_1545'),
        ('accounts', '0008_merge_20180620_0328'),
    ]

    operations = [
    ]
