# Generated by Django 2.0.4 on 2018-08-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180714_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='travel_confirm',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('-', 'Not Decided')], default='-', max_length=1),
        ),
    ]
