# Generated by Django 2.0.4 on 2018-07-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20180620_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('-', 'Not Decided')], default='-', max_length=1),
        ),
    ]
