# Generated by Django 2.0.4 on 2018-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='travel_reimbursement',
            field=models.CharField(choices=[('-', 'Not Decided'), ('Rejected', 'Rejected'), ('Regional', 'Regional'), ('Midwest', 'Midwest'), ('West', 'West'), ('International', 'International')], default='-', max_length=13),
        ),
    ]
