# Generated by Django 2.0.4 on 2018-09-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_travel_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
