# Generated by Django 2.0.4 on 2018-07-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180711_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receipt_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_confirm',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('-', 'Not Decided')], default='-', max_length=1),
        ),
    ]
