# Generated by Django 2.0.4 on 2018-09-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_team_name'),
        ('accounts', '0012_auto_20180723_2337'),
    ]

    operations = [
    ]
