# Generated by Django 2.0.4 on 2018-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20180907_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered',
            field=models.CharField(choices=[('Not registered', 'Not registered'), ('Registered', 'Registered')], default='Not registered', max_length=50),
        ),
    ]
