# Generated by Django 2.0.4 on 2018-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voted',
            field=models.IntegerField(default=0),
        ),
    ]
