# Generated by Django 2.0.4 on 2018-09-07 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registerTeamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(blank=True, default='-', max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rtapp',
            name='user',
        ),
        migrations.AddField(
            model_name='rtapp',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rtapp',
            name='team_name',
            field=models.CharField(blank=True, choices=[('-', 'None'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], default='-', max_length=100, null=True),
        ),
    ]
