# Generated by Django 2.0.4 on 2018-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerTeamApp', '0002_auto_20180907_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtapp',
            name='team_name',
            field=models.CharField(blank=True, choices=[('5 Timmies', '5 Timmies'), ('AI Socrates ', 'AI Socrates '), ('AYA', 'AYA'), ('Aviral', 'Aviral'), ('BaLITmore', 'BaLITmore'), ('Bandwidth', 'Bandwidth'), ('BeMetal', 'BeMetal'), ('Beans in a Can', 'Beans in a Can'), ('Big Brains', 'Big Brains'), ('Blank', 'Blank'), ('Byte Me', 'Byte Me'), ('Cas9', 'Cas9'), ('Charcom', 'Charcom'), ('Citizen Scientist', 'Citizen Scientist'), ('Core 4', 'Core 4'), ('Crypto Card', 'Crypto Card'), ('Davdon', 'Davdon'), ('Deacons', 'Deacons'), ('Dkim', 'Dkim'), ('Doctoc', 'Doctoc'), ('Dr.Gram', 'Dr.Gram'), ('E-connect', 'E-connect'), ('E.P.I.C', 'E.P.I.C'), ('EMS Now', 'EMS Now'), ('Featherfall ', 'Featherfall '), ('Five Factorial', 'Five Factorial'), ('Flow Source', 'Flow Source'), ('Fugal', 'Fugal'), ('Genius Bar', 'Genius Bar'), ('Glove On', 'Glove On'), ('Groceries', 'Groceries'), ('HTNhelp', 'HTNhelp'), ('HealthOverall', 'HealthOverall'), ('High five', 'High five'), ('Humpty Dumpties ', 'Humpty Dumpties '), ('ICU On The Map', 'ICU On The Map'), ('IDrops', 'IDrops'), ('InfoMed', 'InfoMed'), ('Its Like NLP... But For Team Names', 'Its Like NLP... But For Team Names'), ('JEL', 'JEL'), ('JERS', 'JERS'), ('JK', 'JK'), ('Just Pick Something', 'Just Pick Something'), ('KALE', 'KALE'), ('Klear', 'Klear'), ('LAMA TECH', 'LAMA TECH'), ('Lucky Penny', 'Lucky Penny'), ('MedCircle', 'MedCircle'), ('MedShield', 'MedShield'), ('Medplex', 'Medplex'), ('Melanotix', 'Melanotix'), ('Michigan', 'Michigan'), ('Midnight Mavericks', 'Midnight Mavericks'), ('Midwest is Best', 'Midwest is Best'), ('Mira', 'Mira'), ('Neurons', 'Neurons'), ('No More Headaches', 'No More Headaches'), ('Noti-Fall', 'Noti-Fall'), ('NutriDoc', 'NutriDoc'), ('OTC', 'OTC'), ('Parachi', 'Parachi'), ('Physia', 'Physia'), ('Prometheus', 'Prometheus'), ('Purple South African Flying Chinchillas', 'Purple South African Flying Chinchillas'), ('QStroke', 'QStroke'), ('Qcumber', 'Qcumber'), ('QuickFix`', 'QuickFix`'), ('Rehabilita ', 'Rehabilita '), ('S(Team)D', 'S(Team)D'), ('Safety fit', 'Safety fit'), ('Sandwich', 'Sandwich'), ('Scarlet Screw', 'Scarlet Screw'), ('Scribbz', 'Scribbz'), ('Scribr', 'Scribr'), ('Scrubs', 'Scrubs'), ('Sick Day Forecast', 'Sick Day Forecast'), ('Snowballerz', 'Snowballerz'), ('Something Too Edgy', 'Something Too Edgy'), ('Spaghetti', 'Spaghetti'), ('Spiro', 'Spiro'), ('Stimtooth', 'Stimtooth'), ('TBD', 'TBD'), ('TEAM-NAME?', 'TEAM-NAME?'), ('TackTile', 'TackTile'), ('Team Awesome Sauce', 'Team Awesome Sauce'), ('Team Champs', 'Team Champs'), ('Team Johnny', 'Team Johnny'), ('Team Number 1', 'Team Number 1'), ('Team Slogs', 'Team Slogs'), ('The Fellas', 'The Fellas'), ('The Fellas 2.0', 'The Fellas 2.0'), ('The Frazzled Five', 'The Frazzled Five'), ('The Rices', 'The Rices'), ('The pirates', 'The pirates'), ('Tumor Detectives ', 'Tumor Detectives '), ('UR IN LIFE', 'UR IN LIFE'), ('UniOne', 'UniOne'), ('Uprising', 'Uprising'), ('We Hax', 'We Hax'), ('WikiMed', 'WikiMed'), ('Will code for food', 'Will code for food'), ('Yellow Yackets', 'Yellow Yackets'), ('ZZG', 'ZZG'), ('iBioBroskis', 'iBioBroskis'), ('iBioMed', 'iBioMed')], default='-', max_length=100, null=True),
        ),
    ]
