# Generated by Django 2.0.4 on 2018-09-03 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerTeamApp', '0002_rtapp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtapp',
            name='user',
            field=models.ForeignKey(default='na', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
