# Generated by Django 2.0.4 on 2018-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerTeamApp', '0007_auto_20180909_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtapp',
            name='votes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
