# Generated by Django 2.0.4 on 2018-09-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerTeamApp', '0008_rtapp_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtapp',
            name='team_name',
            field=models.CharField(blank=True, choices=[('A. I. Socrates for Orthopaedic Education', 'A. I. Socrates for Orthopaedic Education'), ('AMY, the medical assistant', 'AMY, the medical assistant'), ('Ambient', 'Ambient'), ('AquaMap', 'AquaMap'), ('Arthritis Aid', 'Arthritis Aid'), ('Bandwidth', 'Bandwidth'), ('Bringing Queer Data to the Marketplace', 'Bringing Queer Data to the Marketplace'), ('CARE', 'CARE'), ('CardiaVox', 'CardiaVox'), ('CareFall', 'CareFall'), ('Caring for Caregivers', 'Caring for Caregivers'), ('Child Champs', 'Child Champs'), ('Citizen Scientist', 'Citizen Scientist'), ('CloseCare', 'CloseCare'), ('Concussion detection', 'Concussion detection'), ('Crypto Nexus', 'Crypto Nexus'), ('DisAppter', 'DisAppter'), ('Doctoc', 'Doctoc'), ('Donor Book', 'Donor Book'), ('Dr. Gram', 'Dr. Gram'), ('EEG Simulator', 'EEG Simulator'), ('EZ-EMT', 'EZ-EMT'), ('Food Alert', 'Food Alert'), ('FoodPrint', 'FoodPrint'), ('FoodShare.me', 'FoodShare.me'), ('Fugal', 'Fugal'), ('GloveON!', 'GloveON!'), ('Health E-Connect', 'Health E-Connect'), ('HealthHive', 'HealthHive'), ('InfoMed', 'InfoMed'), ('InforMED', 'InforMED'), ('LBB', 'LBB'), ('LeviChair', 'LeviChair'), ('Lula', 'Lula'), ('Lumisoap', 'Lumisoap'), ('MIRA', 'MIRA'), ('MIRROR App', 'MIRROR App'), ('MakeTheLeap', 'MakeTheLeap'), ('MeChat', 'MeChat'), ('Medplex', 'Medplex'), ('Meds2You', 'Meds2You'), ('Melanotix', 'Melanotix'), ('Meno BOT', 'Meno BOT'), ('Mental Moments', 'Mental Moments'), ('Mind Watch', 'Mind Watch'), ('MinuteMed', 'MinuteMed'), ('MirageMap', 'MirageMap'), ('MoCli', 'MoCli'), ('MyHealth Allies', 'MyHealth Allies'), ('Nearby Nutrition', 'Nearby Nutrition'), ('Noti-Fall', 'Noti-Fall'), ('NutriDoc', 'NutriDoc'), ('NutriLyfe', 'NutriLyfe'), ('O.D. Guard', 'O.D. Guard'), ('Patrick_I/O', 'Patrick_I/O'), ('Physia', 'Physia'), ('Piece of Mind', 'Piece of Mind'), ('PillPix', 'PillPix'), ('PlacePredicts!', 'PlacePredicts!'), ('Pocket Pills', 'Pocket Pills'), ('Pronto Perio Probe', 'Pronto Perio Probe'), ('Pure Palm', 'Pure Palm'), ('QR Cross', 'QR Cross'), ('QStroke', 'QStroke'), ('R(eye)covery', 'R(eye)covery'), ('Rehabilita', 'Rehabilita'), ('SafelyFit', 'SafelyFit'), ('Scribr', 'Scribr'), ('Share The Love', 'Share The Love'), ('Sick Day Forecast', 'Sick Day Forecast'), ('SlowDown!', 'SlowDown!'), ('Stay Hydrated', 'Stay Hydrated'), ('Strive', 'Strive'), ('SymptoKey', 'SymptoKey'), ('TackTile', 'TackTile'), ('Texting Patients', 'Texting Patients'), ('The Gina Gown', 'The Gina Gown'), ('The Prometheus Network', 'The Prometheus Network'), ('Translational Medicine:sisu', 'Translational Medicine:sisu'), ('TriTag', 'TriTag'), ('Uplift', 'Uplift'), ('ZipFood', 'ZipFood'), ('headER', 'headER'), ('iFitness', 'iFitness'), ('iTake', 'iTake'), ('internal journal', 'internal journal'), ('my.Doctor', 'my.Doctor'), ('nurture', 'nurture'), ('zzg', 'zzg')], default='-', max_length=100, null=True),
        ),
    ]
